account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

tasks/urls.py
from django.urls import path

from tasks.views import TasksListView, CreateTaskView, complete_task, delete_task, TodayListView, TomorrowListView, \
    ExpiredTasksView, chart

app_name = 'task'


urlpatterns = [
    path('', TasksListView.as_view(), name='index'),
    path('category/<slug:category_slug>/', TasksListView.as_view(), name='category'),
    path('results/', TasksListView.as_view(), name='searching'),
    path('add', CreateTaskView.as_view(), name='create_task'),
    path('task/complete/', complete_task, name='complete_task'),
    path('task/delete/', delete_task, name='delete_task'),
    path('today/', TodayListView.as_view(), name='tasks_for_today'),
    path('tomorrow/', TomorrowListView.as_view(), name='tasks_for_tomorrow'),
    path('expired/', ExpiredTasksView.as_view(), name='expired_tasks'),
    path('pie-chart/', chart, name='pie-chart')
]

todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('account/', include('account.urls'))
]

account/models.py
from django.db import models

# Create your models here.

tasks/models.py
from datetime import datetime, date, timedelta

from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

TASK_PRIORITIES = (
    (0, 'Low'),
    (1, 'Normal'),
    (2, 'High')
)

TASKS_STATUSES = (
    ('DL', 'Deleted'),
    ('NW', 'New'),
    ('EXP', 'Expired'),
    ('OK', 'Completed')
)


class Category(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=150,  unique=True)
    slug = models.SlugField(max_length=150)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"
        ordering = ['name']

    @classmethod
    def get_user_categories(cls, request):
        return cls.objects.filter(owner=request.user)

    def get_absolute_url(self):
        return reverse('task:category', args=[self.slug])

    def __str__(self):
        return self.name


class Task(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=150)
    content = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    priority = models.PositiveIntegerField(choices=TASK_PRIORITIES, default=0)
    timestamp = models.DateTimeField(auto_now_add=True)
    day_to_perform = models.DateField()
    status = models.CharField(choices=TASKS_STATUSES, default='NW', max_length=3)
    day_of_status_change = models.DateField(blank=True, null=True)

    @classmethod
    def get_user_tasks(cls, request):
        return cls.objects.filter(owner=request.user)

    def get_filtered_by_category_tasks(self, category):
        return super(Task, self).objects.filter(category=category)

    @classmethod
    def change_status(cls, task_id, status):
        try:
            task = cls.objects.get(id=task_id)
            task.status = status
            task.day_of_status_change = date.today()
            task.save()
        except: ObjectNotFound

    class Meta:
        ordering = ["day_to_perform"]

    def __str__(self):
        return self.title

    @classmethod
    def get_completed_tasks_per_day(cls, request):
        days = []
        count = []
        for i in range(5):
            day = date.today() - timedelta(days=i)
            c = cls.get_user_tasks(request).filter(status='OK').filter(day_of_status_change=day).count()
            days.append(day.strftime("%d/%m/%Y"))
            count.append(c)
        return days, count

    @classmethod
    def get_number_of_tasks_by_status(cls, request):
        label = ['Completed', 'Deleted', 'Expired']
        users_tasks = cls.get_user_tasks(request)
        data = []
        data.append(users_tasks.filter(status='OK').count())
        data.append(users_tasks.filter(status='DL').count())
        data.append(users_tasks.filter(status='EXP').count())
        return label, data

tasks/forms.py
from django.forms import forms

account/views.py
from django.shortcuts import render

# Create your views here.

tasks/views.py
import datetime
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, CreateView, FormView

from .models import Category, Task


class TasksListView(ListView):
    paginate_by = 10
    template_name = 'index.html'
    model = Task
    context_object_name = 'tasks'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['categories'] = Category.get_user_categories(self.request)
        return context

    def get_queryset(self):
        query = self.request.GET.get('q')
        qs = super().get_queryset().filter(owner=self.request.user).filter(status='NW')
        if query:
            qs = qs.filter(Q(title__icontains=query) | Q(content__icontains=query))
        return qs

    def get(self, request, *args, category_slug=None):
        category = None
        self.object_list = self.get_queryset()
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            self.object_list = self.get_queryset().filter(category=category)
        context = self.get_context_data()
        context['category'] = category
        return self.render_to_response(context)


class TodayListView(TasksListView):
    def get_queryset(self):
        qs = super().get_queryset().filter(day_to_perform=datetime.date.today())
        return qs


class TomorrowListView(TasksListView):
    def get_queryset(self):
        qs = super().get_queryset().filter(day_to_perform=datetime.date.today() + datetime.timedelta(days=1))
        return qs


class ExpiredTasksView(TasksListView):
    def get_queryset(self):
        qs = Task.objects.filter(owner=self.request.user).filter(status='EXP')
        return qs


class CreateTaskView(CreateView):
    model = Task
    fields = ['title', 'content', 'priority', 'day_to_perform', 'category']
    template_name = 'add_task.html'
    success_url = reverse_lazy('task:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.save()
        return super(CreateTaskView, self).form_valid(form)


@csrf_exempt
def complete_task(request):
    if request.is_ajax():
        task_id = request.GET.get('task_id')
        Task.change_status(task_id, 'OK')
        return JsonResponse({'status': 'Ok'})


@csrf_exempt
def delete_task(request):
    if request.is_ajax():
        task_id = request.GET.get('task_id')
        Task.change_status(task_id, 'DL')
        return JsonResponse({'status': 'Ok'})


def chart(request):
    pie_chart = Task.get_completed_tasks_per_day(request)
    bar_chart = Task.get_number_of_tasks_by_status(request)
    return render(request, 'pie_chart.html', {
        'labels': pie_chart[0],
        'data': pie_chart[1],
        'labels1': bar_chart[0],
        'data1': bar_chart[1]
    })

templates/add_task.html
{% load crispy_forms_tags %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<form method="post" style="margin: 5% 15%;">{% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-success">Create task</button>
</form>

templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/navbar.js' %}"></script>
    <script src="{% static 'js/sort_table.js' %}"></script>
    <title>Django Bootstrap forms</title>
  </head>
  <body>
   <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="">Hi {{ request.user.username }}</a>
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarCollapse"
    aria-controls="navbarCollapse"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto sidenav" id="navAccordion">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'task:create_task'%}">Add task<span class="sr-only"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Item 1</a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link nav-link-collapse"
              href="#"
              id="hasSubItems"
              data-toggle="collapse"
              data-target="#collapseSubItems2"
              aria-controls="collapseSubItems2"
              aria-expanded="false"
            >By date</a>
            <ul class="nav-second-level collapse" id="collapseSubItems2" data-parent="#navAccordion">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'task:tasks_for_today' %}">
                  <span class="nav-link-text">For today</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'task:tasks_for_tomorrow' %}">
                  <span class="nav-link-text">For tomorrow</span>
                </a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Item 3</a>
          </li>
          <li class="nav-item">
            <a
              class="nav-link nav-link-collapse"
              href="#"
              id="hasSubItems"
              data-toggle="collapse"
              data-target="#collapseSubItems4"
              aria-controls="collapseSubItems4"
              aria-expanded="false"
            >By category</a>
            <ul class="nav-second-level collapse" id="collapseSubItems4" data-parent="#navAccordion">
              {% for category in categories %}
              <li class="nav-item">
                <a class="nav-link" href="{{ category.get_absolute_url }}">
                  <span class="nav-link-text">{{ category.name }}</span>
                </a>
              </li>
              {% endfor %}
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'task:expired_tasks' %}">Expired</a>
          </li>
        </ul>
        <form class="form-inline ml-auto mt-2 mt-md-0" method="GET" action="{% url 'task:searching' %}">
          <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="q" value="{{request.GET.q}}">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>

    <main class="content-wrapper">
      <div class="container-fluid">
        {% if category %}
        <h1>{{ category.name }}</h1>
        {% endif %}
        <table class="table table-striped" id="myTable">
          <thead>
            <tr>
              <th scope="col" onclick="sortTable(0)">Title</th>
              <th scope="col"onclick="sortTable(1)">Priority</th>
              <th scope="col">Date</th>
              <th scope="col">Complete</th>
              <th scope="col">Delete</th>
            </tr>
          </thead>
          <tbody>
          {% for task in tasks|dictsort:"title" %}
            <tr id="{{ task.id }}">
              <th scope="row">{{ task.title }}</th>
              <td>{{ task.get_priority_display}}</td>
              <td>{{ task.day_to_perform }}</td>
              <td><button id="complete">Complete</button></td>
              <td><button id="delete">Delete</button></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
    </main>

    <footer class="footer">
      <div class="container">
          <div class="text-center">
              <span>Footer</span>
          </div>
      </div>
    </footer>
    </div>
  </body>
</html>
<script>
$(document).ready(function () {
 $("#myTable").on('click', '#complete', function (){
   var id = $(this).parent().parent().attr('id')
     $.ajax({
            type:'GET',
            url:  '{% url "task:complete_task" %}',
            data:{
                task_id: id,
                datatype: 'json',
            },
            success: function(data){
                $('#'+id).remove();
           },
            error : function(xhr,errmsg,err) {
            console.log(xhr.status + ": " + xhr.responseText);
        }
        });
   });
   $("#myTable").on('click', '#delete', function (){
   var id = $(this).parent().parent().attr('id')
     $.ajax({
            type:'GET',
            url:  '{% url "task:delete_task" %}',
            data:{
                task_id: id,
                datatype: 'json',
            },
            success: function(data){
                $('#'+id).remove();
           },
            error : function(xhr,errmsg,err) {
            console.log(xhr.status + ": " + xhr.responseText);
        }
        });
   });
});
</script>

templates/pie_chart.html
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
<canvas id="bar-chart" width="400" height="100"></canvas>
<canvas id="pie-chart" width="800" height="450"></canvas>

<script>
new Chart(document.getElementById("bar-chart"), {
    type: 'bar',
    data: {
      labels: {{labels|safe}},
      datasets: [
        {
          label: "Population (millions)",
          backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
          data: {{data|safe}}
        }
      ]
    },
    options: {
      legend: { display: false },
      title: {
        display: true,
        text: 'Predicted world population (millions) in 2050'
      }
    }
});
new Chart(document.getElementById("pie-chart"), {
    type: 'pie',
    data: {
      labels: {{labels1|safe}},
      datasets: [{
        label: "Population (millions)",
        backgroundColor: ["#3e95cd", "#8e5ea2","#3cba9f","#e8c3b9","#c45850"],
        data: {{data|safe}}
      }]
    },
    options: {
      title: {
        display: true,
        text: 'Predicted world population (millions) in 2050'
      }
    }
});
</script>